### ISSUE TITLE
Can openadms-server run under Windows system?

### ISSUE THREAD

**Issue by geovey** [dabamos/openadms-server#1]
I installed the postgresql database under the Windows system, and created the <username> and <database> using timeseries.sql according to the README.md requirements of openadms-server. At the same time, configure the nginx.conf file in Windows, but it always fails. 
2020-09-01T16:21:57 -     INFO -              cloudExporter - Sending observation "getValues" of target "Mosaic-X5" from port "com1" to API "https://192.168.31.144/api/v1/observations/" ...
2020-09-01T16:22:56 -  WARNING -              cloudExporter - Connection to API "https://192.168.31.144/" failed

I have noticed that README.md describes the operation under FreeBSD or Linux system, but my server is installed with Windows system.

**Comment by interkosmos** [comment]
In order to store observation data inside your PostgreSQL database you first have to set-up [OpenResty](https://github.com/openresty/openresty/blob/master/doc/README-windows.md) as a web-based service. The CloudExporter module sends observations only to this HTTP service, which handles the PostgreSQL access. Make sure to compile all required 3rd party nginx modules into OpenResty, specifically:

* [form-input](https://github.com/calio/form-input-nginx-module)
* [headers-more](https://github.com/openresty/headers-more-nginx-module)
* [http-realip](http://nginx.org/en/docs/http/ngx_http_realip_module.html)
* [lua](https://github.com/openresty/lua-nginx-module)
* [postgres](https://github.com/FRiCKLE/ngx_postgres)
* [set-misc](https://github.com/openresty/set-misc-nginx-module)

If you really want to connect to Postgres directly you will have to write your own OpenADMS Node module, probably based on [Psycopg](https://www.psycopg.org/docs/). You don’t have to write the SQL queries yourself, just call the PLpgSQL stored procedures. For example, to store an observation data object in JSON format, run the SQL query `SELECT openadms.store_observation(<json>)`. See also the [documentation](https://www.dabamos.de/manual/openadms-server/introduction.html).

**Comment by geovey** [comment]
Thank you for your answer;

I've learned that it's not easy to compile nginx or openresty under windows.

Maybe I should choose Linux as the server.

**Comment by interkosmos** [comment]
Yeah, it’s probably easier if you set up a virtual machine with Linux. Feel free to open this issue again.
